USE [Teste]
GO

IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NotaFiscalItem' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'BaseIpi' 
)
BEGIN
	ALTER TABLE NotaFiscalItem ADD BaseIpi DECIMAL(18, 5) null
END

GO

IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NotaFiscalItem' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'AliquotaIpi' 
)
BEGIN
	ALTER TABLE NotaFiscalItem ADD AliquotaIpi DECIMAL(18, 5) null
END

GO

IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NotaFiscalItem' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'ValorIpi' 
)
BEGIN
	ALTER TABLE NotaFiscalItem ADD ValorIpi DECIMAL(18, 5) null
END

GO

IF NOT EXISTS (
	SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NotaFiscalItem' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'Desconto' 
)
BEGIN
	ALTER TABLE NotaFiscalItem ADD Desconto DECIMAL(18, 5) null
END